yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="posts"),
    path("create/", views.post_create, name="new_post"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="update_post"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow"
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("posts.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls")),
]

handler500 = "core.views.server_error"
handler404 = "core.views.page_not_found"
handler403 = "core.views.csrf_failure"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(verbose_name="Название группы", max_length=200)
    slug = models.SlugField(
        verbose_name="Уникальный адрес группы", max_length=500, unique=True
    )
    description = models.TextField(verbose_name="Описание группы")

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="Текст поста")
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор поста"
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name="posts",
        null=True,
        blank=True,
        verbose_name="Группа",
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ("-pub_date",)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост, к которому оставлен комментарий"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор комментария"
    )
    text = models.TextField(verbose_name="Текст комментария")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации"
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Блогер"
    )

    def __str__(self):
        return f"{self.user} подписан на {self.author}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follow")
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        help_texts = {
            "text": "Текст комментария",
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def make_paginator(request, post_list):
    PAGES: int = 10
    paginator = Paginator(post_list, PAGES)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20, key_prefix="index_page")
def index(request):
    post_list = Post.objects.all()
    page_obj = make_paginator(request, post_list)

    context = {"page_obj": page_obj, "user": request.user}
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group_list = group.posts.all().select_related("group")
    page_obj = make_paginator(request, group_list)

    context = {
        "group": group,
        "page_obj": page_obj,
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all().select_related("author")
    page_obj = make_paginator(request, post_list)

    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=user).exists()
    )

    context = {"username": user, "page_obj": page_obj, "following": following}
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()

    context = {
        "post": post,
        "form": form,
        "comments": comments,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post_form = form.save(commit=False)
        post_form.author = request.user
        post_form.save()
        return redirect("posts:profile", request.user)

    return render(
        request,
        "posts/create_or_update_post.html",
        {"form": form},
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    if post.author != request.user:
        return redirect("posts:post_detail", post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)

    return render(
        request,
        "posts/create_or_update_post.html",
        {"form": form, "is_edit": is_edit, "post_id": post_id},
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    user = get_object_or_404(User, username=request.user)
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = make_paginator(request, post_list)

    context = {"page_obj": page_obj, "user": user}

    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    user = get_object_or_404(User, username=username)
    if request.user != user:
        Follow.objects.get_or_create(user=request.user, author=user)

    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect("posts:profile", username)

yatube/templates/includes/comment.html
<div class="media-body">
  <h5 class="mt-0">
    <a href="{% url 'posts:profile' comment.author.username %}">
      {{ comment.author.username }}
    </a>
  </h5>
  <p>
    {{ comment.text }}
  </p>
</div>

yatube/templates/includes/comment_form.html
{% load user_filters %}
<div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
</div>

yatube/templates/includes/follow_button.html
{% if following %}
<a
  class="btn btn-lg btn-light"
  href="{% url 'posts:profile_unfollow' username.username %}" role="button"
>
  Отписаться
</a>
{% else %}
  <a
    class="btn btn-lg btn-primary"
    href="{% url 'posts:profile_follow' username.username %}" role="button"
  >
    Подписаться
  </a>
{% endif %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:posts' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">
          Технологии
        </a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:new_post' %}">Новая запись</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:reset_password' %}active{% endif %}" href="{% url 'users:reset_password' %}">
          Изменить пароль
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">
          Выйти
        </a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">
          Войти
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">
          Регистрация
        </a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/includes/post.html
{% load thumbnail %}
<article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        {% if username %}
          <a href="{% url 'posts:profile' username %}">все посты пользователя</a>
         {% endif %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    {% if username %}
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a></br>
    {% endif %}
    {% if post.group and not group %}
        <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
    {% endif %}
</article>
{% if not forloop.last %}
    <hr>
{% endif %}

yatube/templates/includes/post_form.html
{% load user_filters %}
<div class="card-header">
{% if is_edit %}
    Редактировать пост
{% else %}
    Новый пост
{% endif %}
</div>
<div class="card-body">
      {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
      {% endif %}

    {% if is_edit %}
    <form method="post" enctype="multipart/form-data" action="{% url 'posts:update_post' post_id %}">
    {% endif %}
    <form method="post" enctype="multipart/form-data" action="{% url 'posts:new_post' %}">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group row my-3 p-3">
      <label>
          {{ field.label_tag }}
          {% if field.field.required %}
              <span class="required text-danger">*</span>
          {% endif %}
       </label>
      {{ field|addclass:'form-control' }}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    </div>
    {% endfor %}
    <div class="d-flex justify-content-end">
        {% if is_edit %}
      <button type="submit" class="btn btn-primary">
          Добавить
      </button>
        {% else %}
       <button type="submit" class="btn btn-primary">
        Сохранить
       </button>
        {% endif %}
    </div>
</form>
</div>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:posts' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}